version: "3"

services:
  backend:
    container_name: mailer-django
    build:
      context: ./server
    volumes:
      - ./server/:/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
      - ./server/.env
    stdin_open: true
    tty: true

  db:
    container_name: mailer-postgres
    restart: always
    image: postgres:10.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev

  frontend:
    container_name: mailer-react
    build:
      context: ./client
    volumes:
      - ./client:/app/
      - ./client/node_modules:/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
