# Generated by Django 3.1.7 on 2021-03-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfig",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RssLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rss_links",
                        to="emails.emailconfig",
                    ),
                ),
            ],
        ),
    ]
